### ISSUE TITLE
Integrate EBC_Tutorial code of network drive U into EBC-Tutorials on Github

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/EBC-Tutorials#14]
The tutorial with some Python example codes should be moved to this repo.

**Comment by PMehrfeld** [comment]
@JSchiefelbein: Thanks a lot for this valuable contribution.
Anyway I would suggest to integrate your basic coding tutorial into the current Readme.md structure at the top level of our python tutorial. My proposal is to insert it between current 4th and 5th (this means before "Advanced concepts". A suggestions for naming would be something like "Basic coding" instead of "Basic tutorial" within the folder "ebc_basic_tutorial".

What do you think?

**Comment by JSchiefelbein** [comment]
Sure, sounds fine with me. I can just move and rename the basic tutorial

**Comment by PMehrfeld** [comment]
Perfect, thanks!
And do not forget to enhance the table of contents ;)

**Comment by PMehrfeld** [comment]
Closed via #17
