### ISSUE TITLE
"Wrong" (?) status before pull?

### ISSUE THREAD

**Issue by mahoffmann** [RWTH-EBC/EBC-Tutorials#3]
The picture showing git status before the pull command
command: git checkout ~~status~~ master
answer: "your branch is up to date with origin/master"
(search for "We can do this by calling git checkout master:" ; so I adress the picture following that line)

I didn't get if that is an accident or intendet. If intended: I don't understand, because I thought it shouldn't be up to date until after the pull.

offtopic: hahaaaa, ein Issue, ein Issue.. Erster! :-)

**Comment by PRemmen** [comment]
@mahoffmann 
That is a bit tricky and you are right that this is not really user friendly. 

First of all to remember: `git status` alone will always return differences between the current working version ("snaphsot") since your last local commit. 

But why does it tell that it is up-to-date with `origin/master` ? 

In this case `origin/master` is a local reference to a specific commit (which is a reference to your last local commit, see above) and at the same time it tells you that this reference tracks (or "is connected to") a remote (`origin`) branch (`master`). To compare differences between the remote branch (`origin/master`) you first need to get the information of this branch. You can do that by
`git fetch` 
and then
`git status`
Now git status will tell you the differences between the new reference (which now is the remote commit) and your "snapshot".

I hope this answers your question. I questioned this myself some time ago and I agree that this is confusing. Maybe it is worthwhile mentioning this in the tutorial? @marcusfuchs

**Comment by marcusfuchs** [comment]
I agree that this should be mentioned in the tutorial. Any volunteers to add this?

**Comment by mahoffmann** [comment]
I'll give it a try...

**Comment by mahoffmann** [comment]
Professionally included a spelling mistake leaving out the G of git... if someone can correct that "on the fly" or whatever?

**Comment by marcusfuchs** [comment]
This is on the master now.
